/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IFlareCallee,
  IFlareCalleeInterface,
} from "../../../tokens/FlarePair.sol/IFlareCallee";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "uniswapV2Call",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFlareCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IFlareCalleeInterface {
    return new utils.Interface(_abi) as IFlareCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFlareCallee {
    return new Contract(address, _abi, signerOrProvider) as IFlareCallee;
  }
}
